(ns one.dom)

(def ^:react-component div "div")
(def ^:react-component a "a")
(def ^:react-component p "p")
(def ^:react-component span "span")
(def ^:react-component ul "ul")
(def ^:react-component li "li")
(def ^:react-component h1 "h1")
(def ^:react-component label "label")
(def ^:react-component strong "strong")
(def ^:react-component input "input")
(def ^:react-component button "button")
(def ^:react-component footer "footer")
(def ^:react-component header "header")
(def ^:react-component section "section")
(def ^:react-component aside "aside")
